/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Fira Code', 'monospace'],
        'headline-xl': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'code-sm': ['Fira Code', 'monospace'],
      },
      colors: {
        "on-primary-fixed-variant": "#00458e",
        "glass-border": "rgba(229, 231, 235, 0.5)",
        "on-secondary-container": "#00714d",
        "outline": "#1a1a1a",
        "on-primary": "#ffffff",
        "primary-container": "#0066cc",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#dce2f3",
        "on-primary-fixed": "#001b3e",
        "surface-bg": "#ffffff",
        "secondary-container": "#6cf8bb",
        "primary": "#1a1a1a",
        "on-surface-variant": "#414753",
        "error": "#ba1a1a",
        "secondary-fixed": "#6ffbbe",
        "surface-container-high": "#e2e8f8",
        "surface": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "secondary": "#006c49",
        "alert-red": "#EF4444",
        "on-tertiary-fixed": "#2a1700",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dce2f3",
        "on-background": "#151c27",
        "tertiary-container": "#935c00",
        "surface-dim": "#d3daea",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed": "#002113",
        "inverse-primary": "#aac7ff",
        "on-tertiary-container": "#ffe4c7",
        "primary-fixed": "#d7e3ff",
        "primary-fixed-dim": "#aac7ff",
        "tertiary": "#724700",
        "on-primary-container": "#dfe8ff",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#ebf1ff",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#1a1a1a",
        "background": "#ffffff",
        "on-surface": "#1a1a1a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-tint": "#005cba",
        "inverse-surface": "#2a313d",
        "surface-container": "#e7eefe",
        "on-secondary-fixed-variant": "#005236",
        "charcoal": "#1F2937",
        "surface-container-low": "#f0f3ff",
        "brand-accent": "#ff3366",
        "relief-accent": "#008080",
        // Keep compat fallback aliases
        "clinical-black": "#1a1a1a",
      },
      spacing: {
        'gutter': '1.5rem',
        'component-gap': '0.5rem',
        'container-padding': '2rem',
        'sidebar-width': '280px',
        'evidence-panel-width': '320px',
        'stack-gap': '1rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-in-up': 'fadeInUp 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'skeleton': 'skeleton 2s ease-in-out infinite',
        'spin-slow': 'spin 10s linear infinite',
        'spin-slower-reverse': 'spin 6s linear infinite reverse',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        skeleton: {
          '0%': { opacity: '0.5' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
}
