"""initial schema

Revision ID: 6591c05540dc
Revises: 
Create Date: 2026-07-11 17:53:02.708051

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6591c05540dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
